
export const GET_ALL_CONTACTS = "GET-ALL-CONTACTS";
export const CONTACTS_SUCCESS= "CONTACTS_SUCCESS";
export const CONTACTS_ERROR = "CONTACTS_ERROR";
export const CREATE_CONTACT='CREATE_CONTACT'
export const CREATE_CONTACT_SUCCESS='CREATE_CONTACT'
export const CREATE_CONTACT_ERROR='CREATE_CONTACT'
export const DELETE_CONTACT='DELETE_CONTACT'
export const DELETE_CONTACT_SUCCESS='DELETE_CONTACT'
export const DELETE_CONTACT_ERROR='DELETE_CONTACT'